version: '3.9'
services:

  app:
    build:
      context: ./../../
      dockerfile: ./docker/prod/Dockerfile
    container_name: app
    image: app
    ports:
      - 8080:8080
    env_file: ./.env
    depends_on:
      - postgres
      - nats
      - redis
      - clickhouse
    volumes:
      - ./logs/:/logs/

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB_NAME}
    ports:
      - "${PG_PORT}:5432"

  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server
    volumes:
      - clickhouse-data:/var/lib/clickhouse/
    ports:
      - 8123:8123
      - 9000:9000
      - 9009:9009
    depends_on:
      - nats
    healthcheck:
      test: wget --no-verbose --tries=1 --spider localhost:8123/ping || exit 1
      interval: 3s
      timeout: 10s
      retries: 5
      start_period: 10s

  nats:
    container_name: nats
    image: nats:2.9.19-alpine3.18
    ports:
      - 8222:8222
      - "${NATS_PORT}:4222"

volumes:
  pg-data:
  clickhouse-data:
